"""initial_schema

Revision ID: 323a1fc13be9
Revises: 
Create Date: 2026-04-13 19:21:50.242954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '323a1fc13be9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('FOUNDER', 'COLLABORATOR', 'INVESTOR', 'ADMIN', 'ACCELERATOR_MGR', name='roleenum'), nullable=False),
    sa.Column('subscription_tier', sa.Enum('FREE', 'BUILDER', 'FOUNDER_PRO', 'INVESTOR', 'ENTERPRISE', name='subscriptiontierenum'), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=True),
    sa.Column('subscription_credits_remaining', sa.Integer(), nullable=False),
    sa.Column('subscription_resets_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('payg_credits_balance', sa.Integer(), nullable=False),
    sa.Column('total_credits_used', sa.Integer(), nullable=False),
    sa.Column('profile_completeness_pct', sa.Float(), nullable=True),
    sa.Column('github_connected', sa.Boolean(), nullable=True),
    sa.Column('linkedin_connected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_table('ai_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prompt_type', sa.Enum('TRAINING', 'TOUR_GUIDE', 'EVALUATION', 'RECOMMENDATION', 'MATCHING', 'RISK_ANALYSIS', 'INVESTOR_SIGNAL', 'UNICORN_ANALYSIS', 'MARKET_INTELLIGENCE', 'BUSINESS_PLAN', 'TECH_ARCHITECTURE', 'EXECUTION_ROADMAP', 'PIVOT_INTELLIGENCE', 'DASHBOARD', 'FEED', 'WORKSPACE', 'ORG_SPHERE', 'PROFILE_ANALYSIS', 'ADMIN_MONITOR', 'INVESTOR_EVI', 'GSIS', name='prompttypeenum'), nullable=False),
    sa.Column('target_role', sa.Enum('FOUNDER', 'COLLABORATOR', 'INVESTOR', 'ADMIN', 'ACCELERATOR_MGR', name='roleenum'), nullable=False),
    sa.Column('min_tier', sa.Enum('FREE', 'BUILDER', 'FOUNDER_PRO', 'INVESTOR', 'ENTERPRISE', name='subscriptiontierenum'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt_template', sa.Text(), nullable=False),
    sa.Column('output_format', sa.Text(), nullable=True),
    sa.Column('credit_cost', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ab_group', sa.String(length=10), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prompt_type_role', 'ai_prompts', ['prompt_type', 'target_role', 'is_active'], unique=False)
    op.create_index('idx_prompt_version', 'ai_prompts', ['name', 'version'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('SUBSCRIPTION_STARTED', 'SUBSCRIPTION_RENEWED', 'SUBSCRIPTION_UPGRADED', 'SUBSCRIPTION_CANCELLED', 'CREDITS_PURCHASED', 'CREDITS_DEDUCTED', 'CREDITS_RESET_MONTHLY', 'CREDITS_REFUNDED', 'PAYWALL_HIT', 'PAYWALL_CONVERTED', 'REFERRAL_CREDIT_EARNED', name='billingeventtypeenum'), nullable=False),
    sa.Column('credits_delta', sa.Integer(), nullable=False),
    sa.Column('credits_after', sa.Integer(), nullable=False),
    sa.Column('from_subscription', sa.Integer(), nullable=True),
    sa.Column('from_payg', sa.Integer(), nullable=True),
    sa.Column('usd_charged_payg', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=True),
    sa.Column('operation_id', sa.String(length=100), nullable=True),
    sa.Column('plan_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_event_type', 'credit_ledger', ['event_type', 'created_at'], unique=False)
    op.create_index('idx_credit_user_created', 'credit_ledger', ['user_id', 'created_at'], unique=False)
    op.create_table('credit_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credits_qty', sa.Integer(), nullable=False),
    sa.Column('amount_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stripe_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_purchase_user', 'credit_purchases', ['user_id'], unique=False)
    op.create_table('document_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('audience', sa.String(length=30), nullable=False),
    sa.Column('style', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('section_schema', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('estimated_pages', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('avg_user_rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('total_uses', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_active', 'document_templates', ['is_active'], unique=False)
    op.create_index('idx_template_type_audience_style', 'document_templates', ['document_type', 'audience', 'style'], unique=False)
    op.create_table('learner_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('project_stage', sa.String(length=20), nullable=True),
    sa.Column('hours_available_per_week', sa.Float(), nullable=True),
    sa.Column('learning_pace', sa.String(length=20), nullable=True),
    sa.Column('target_mvp_weeks', sa.Integer(), nullable=True),
    sa.Column('estimated_weeks_to_mvp', sa.Float(), nullable=True),
    sa.Column('has_technical_skills', sa.Boolean(), nullable=True),
    sa.Column('has_cofounder', sa.Boolean(), nullable=True),
    sa.Column('pre_existing_skills', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('unicorn_score', sa.Float(), nullable=True),
    sa.Column('beta_users_count', sa.Integer(), nullable=True),
    sa.Column('has_revenue', sa.Boolean(), nullable=True),
    sa.Column('investor_interest', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_learner_user', 'learner_profiles', ['user_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('org_type', sa.String(length=50), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('ai_health_score', sa.Float(), nullable=True),
    sa.Column('tss_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_org_owner', 'organizations', ['owner_id'], unique=False)
    op.create_table('paywall_hits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('FOUNDER', 'COLLABORATOR', 'INVESTOR', 'ADMIN', 'ACCELERATOR_MGR', name='roleenum'), nullable=True),
    sa.Column('plan_id', sa.String(length=50), nullable=True),
    sa.Column('operation_id', sa.String(length=100), nullable=True),
    sa.Column('paywall_copy', sa.Text(), nullable=True),
    sa.Column('upgrade_cta', sa.Text(), nullable=True),
    sa.Column('upgrade_plan_id', sa.String(length=50), nullable=True),
    sa.Column('context_vars', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.Column('converted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('hit_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_paywall_operation', 'paywall_hits', ['operation_id', 'converted'], unique=False)
    op.create_index('idx_paywall_user', 'paywall_hits', ['user_id', 'hit_at'], unique=False)
    op.create_table('problem_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('urgency', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('who_is_affected', sa.Text(), nullable=True),
    sa.Column('current_solutions', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('sdg_alignment', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('impact_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('priority_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('engagement_count', sa.Integer(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('stakeholder_map', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('related_problem_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('is_ai_discovered', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_problem_category_urgency', 'problem_nodes', ['category', 'urgency'], unique=False)
    op.create_index('idx_problem_impact_score', 'problem_nodes', ['impact_score'], unique=False)
    op.create_index('idx_problem_priority_score', 'problem_nodes', ['priority_score'], unique=False)
    op.create_index('idx_problem_submitted_by', 'problem_nodes', ['submitted_by'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('stage', sa.Enum('IDEA', 'VALIDATION', 'MVP', 'BETA', 'LAUNCH', 'GROWTH', 'SCALE', name='projectstageenum'), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('gsis_score', sa.Float(), nullable=True),
    sa.Column('unicorn_potential_score', sa.Float(), nullable=True),
    sa.Column('market_readiness_score', sa.Float(), nullable=True),
    sa.Column('investment_score', sa.Float(), nullable=True),
    sa.Column('wcrs_score', sa.Float(), nullable=True),
    sa.Column('evi_score', sa.Float(), nullable=True),
    sa.Column('evi_i_score', sa.Float(), nullable=True),
    sa.Column('pps_score', sa.Float(), nullable=True),
    sa.Column('cis_score', sa.Float(), nullable=True),
    sa.Column('iis_score', sa.Float(), nullable=True),
    sa.Column('days_since_update', sa.Integer(), nullable=True),
    sa.Column('last_milestone_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('decay_factor', sa.Float(), nullable=True),
    sa.Column('compliance_items', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('transparency_items', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_gsis', 'projects', ['gsis_score'], unique=False)
    op.create_index('idx_project_owner', 'projects', ['owner_id'], unique=False)
    op.create_index('idx_project_stage', 'projects', ['stage'], unique=False)
    op.create_index('idx_project_wcrs', 'projects', ['wcrs_score'], unique=False)
    op.create_table('referral_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referrer_id', sa.UUID(), nullable=False),
    sa.Column('referred_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('credits_earned', sa.Integer(), nullable=True),
    sa.Column('usd_credit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('credibility_pts', sa.Integer(), nullable=True),
    sa.Column('free_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_referral_referrer', 'referral_events', ['referrer_id'], unique=False)
    op.create_table('user_skill_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('skill_text', sa.Text(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_embedding', 'user_skill_embeddings', ['user_id'], unique=False)
    op.create_table('agent_execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('VENTURE_INTAKE', 'UNICORN_EVALUATOR', 'MARKET_INTELLIGENCE', 'PRODUCT_FEASIBILITY', 'STARTUP_STRATEGY', 'FINANCE_STRATEGY', 'INVESTOR_INTELLIGENCE', 'BUSINESS_PLAN_GEN', 'TECH_ARCHITECT', 'PIVOT_INTELLIGENCE', 'TOUR_GUIDE', 'ADAPTIVE_TRAINING', 'MATCHING', 'RISK_EVALUATOR', 'WORKSPACE_ASSISTANT', 'FEED_INTELLIGENCE', 'DASHBOARD_INTELLIGENCE', 'AI_PROFILE', 'ORG_SPHERE', 'ADMIN_MONITOR', 'GSIS_COMPUTE', name='agenttypeenum'), nullable=False),
    sa.Column('agent_version', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('trigger_type', sa.String(length=30), nullable=True),
    sa.Column('trigger_event', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('output', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('models_called', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('credits_consumed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_success', 'agent_execution_logs', ['agent_type', 'success'], unique=False)
    op.create_index('idx_agent_type_started', 'agent_execution_logs', ['agent_type', 'started_at'], unique=False)
    op.create_index('idx_agent_user_started', 'agent_execution_logs', ['user_id', 'started_at'], unique=False)
    op.create_table('ai_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('cost', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('credits_consumed', sa.Integer(), nullable=True),
    sa.Column('from_subscription', sa.Integer(), nullable=True),
    sa.Column('from_payg', sa.Integer(), nullable=True),
    sa.Column('usd_charged_payg', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('ip_protected', sa.Boolean(), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['ai_prompts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_output_cost', 'ai_outputs', ['cost'], unique=False)
    op.create_index('idx_output_project', 'ai_outputs', ['project_id'], unique=False)
    op.create_index('idx_output_task_type', 'ai_outputs', ['task_type'], unique=False)
    op.create_index('idx_output_user_created', 'ai_outputs', ['user_id', 'created_at'], unique=False)
    op.create_table('app_scaffolds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scaffold_type', sa.String(length=50), nullable=False),
    sa.Column('stack_description', sa.String(length=255), nullable=True),
    sa.Column('pages', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('schema_sql', sa.Text(), nullable=True),
    sa.Column('api_routes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('env_template', sa.Text(), nullable=True),
    sa.Column('components', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('setup_steps', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('deploy_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('deploy_status', sa.String(length=30), nullable=True),
    sa.Column('github_repo_url', sa.Text(), nullable=True),
    sa.Column('vercel_url', sa.Text(), nullable=True),
    sa.Column('live_preview_url', sa.Text(), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('vercel_deploy_url', sa.Text(), nullable=True),
    sa.Column('estimated_build_hours', sa.Integer(), nullable=True),
    sa.Column('ip_protected', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('credits_consumed', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deployed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scaffold_project', 'app_scaffolds', ['project_id'], unique=False)
    op.create_index('idx_scaffold_type_status', 'app_scaffolds', ['scaffold_type', 'deploy_status'], unique=False)
    op.create_index('idx_scaffold_user', 'app_scaffolds', ['user_id', 'generated_at'], unique=False)
    op.create_table('discussion_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('idea_clusters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('strongest_direction', sa.Text(), nullable=True),
    sa.Column('readiness_confidence', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('is_ready_to_convert', sa.Boolean(), nullable=True),
    sa.Column('contribution_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_thread_problem', 'discussion_threads', ['problem_id'], unique=False)
    op.create_index('idx_thread_ready', 'discussion_threads', ['is_ready_to_convert'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('unicorn_potential_score', sa.Float(), nullable=True),
    sa.Column('unicorn_classification', sa.String(length=50), nullable=True),
    sa.Column('driver_scores', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('venture_viability_report', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('product_feasibility_report', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('market_adoption_report', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('emerging_trend_rating', sa.String(length=10), nullable=True),
    sa.Column('founder_potential_rating', sa.String(length=10), nullable=True),
    sa.Column('demand_evidence_rating', sa.String(length=10), nullable=True),
    sa.Column('growth_control_rating', sa.String(length=10), nullable=True),
    sa.Column('venture_stage', sa.String(length=20), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('full_evaluation_text', sa.Text(), nullable=True),
    sa.Column('swot_analysis', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('key_risks', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eval_project', 'evaluations', ['project_id'], unique=False)
    op.create_index('idx_eval_score', 'evaluations', ['unicorn_potential_score'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('agents_triggered', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_processed', 'event_logs', ['processed', 'created_at'], unique=False)
    op.create_index('idx_event_type_created', 'event_logs', ['event_type', 'created_at'], unique=False)
    op.create_index('idx_event_user', 'event_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('feed_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('post_type', sa.String(length=30), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ai_relevance_score', sa.Float(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('trust_weight', sa.Float(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feed_author', 'feed_posts', ['author_id', 'created_at'], unique=False)
    op.create_index('idx_feed_relevance', 'feed_posts', ['ai_relevance_score'], unique=False)
    op.create_table('generated_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('style', sa.String(length=20), nullable=True),
    sa.Column('audience', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_output', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('page_estimate', sa.Integer(), nullable=True),
    sa.Column('investor_mode', sa.Boolean(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('credits_consumed', sa.Integer(), nullable=True),
    sa.Column('shareable_link', sa.Text(), nullable=True),
    sa.Column('export_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('parent_document_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['parent_document_id'], ['generated_documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_project_type', 'generated_documents', ['project_id', 'document_type'], unique=False)
    op.create_index('idx_doc_type_audience', 'generated_documents', ['document_type', 'audience'], unique=False)
    op.create_index('idx_doc_user', 'generated_documents', ['user_id', 'generated_at'], unique=False)
    op.create_table('idea_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('idea_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('idea_text', sa.Text(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('is_protected', sa.Boolean(), nullable=True),
    sa.Column('leak_detection_enabled', sa.Boolean(), nullable=True),
    sa.Column('leak_detection_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idea_fingerprint'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index('idx_idea_fingerprint', 'idea_embeddings', ['idea_fingerprint'], unique=False)
    op.create_index('idx_idea_project', 'idea_embeddings', ['project_id'], unique=False)
    op.create_table('investor_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investor_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_investor_read', 'investor_alerts', ['investor_id', 'read'], unique=False)
    op.create_table('investor_evi_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('mdr_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('is_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('trv_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('rta_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ugm_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('cev_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('raw_evi_i', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('decay_factor', sa.DECIMAL(precision=6, scale=4), nullable=False),
    sa.Column('adjusted_evi_i', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('signal', sa.String(length=30), nullable=False),
    sa.Column('velocity_risk', sa.String(length=10), nullable=False),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('trend_delta', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('strengths', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('red_flags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('watch_items', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('data_freshness', sa.String(length=10), nullable=True),
    sa.Column('days_since_update', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evi_adjusted', 'investor_evi_snapshots', ['adjusted_evi_i'], unique=False)
    op.create_index('idx_evi_project_computed', 'investor_evi_snapshots', ['project_id', 'computed_at'], unique=False)
    op.create_index('idx_evi_signal', 'investor_evi_snapshots', ['signal', 'computed_at'], unique=False)
    op.create_table('investor_watchlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investor_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('alert_threshold_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_watchlist_investor', 'investor_watchlist', ['investor_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seeker_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('match_type', sa.String(length=30), nullable=False),
    sa.Column('skill_similarity', sa.Float(), nullable=True),
    sa.Column('goal_similarity', sa.Float(), nullable=True),
    sa.Column('execution_style_similarity', sa.Float(), nullable=True),
    sa.Column('availability_overlap', sa.Float(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('domain_experience', sa.Float(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('compatibility_explanation', sa.Text(), nullable=True),
    sa.Column('risk_flags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['seeker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_score', 'matches', ['match_score'], unique=False)
    op.create_index('idx_match_seeker', 'matches', ['seeker_id', 'status'], unique=False)
    op.create_table('org_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_role', sa.String(length=50), nullable=True),
    sa.Column('role_efficiency', sa.Float(), nullable=True),
    sa.Column('joined_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orgmember_org', 'org_members', ['org_id'], unique=False)
    op.create_table('personalised_curricula',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('learner_id', sa.UUID(), nullable=True),
    sa.Column('pre_mvp_module_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_weeks_to_mvp', sa.Float(), nullable=True),
    sa.Column('estimated_hours_to_mvp', sa.Float(), nullable=True),
    sa.Column('weekly_learning_target_hrs', sa.Float(), nullable=True),
    sa.Column('mvp_target_date', sa.String(length=20), nullable=True),
    sa.Column('post_mvp_tracks_available', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('post_mvp_unlocked_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('post_mvp_locked_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_module_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('in_progress_module_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('next_module_id', sa.String(length=20), nullable=True),
    sa.Column('certifications_earned', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('certifications_eligible', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('adaptation_count', sa.Integer(), nullable=True),
    sa.Column('last_adapted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('adaptation_reason', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_curriculum_user', 'personalised_curricula', ['user_id'], unique=False)
    op.create_table('project_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_milestone_project', 'project_milestones', ['project_id'], unique=False)
    op.create_table('prompt_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('total_execs', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('avg_rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('avg_time_ms', sa.Integer(), nullable=True),
    sa.Column('avg_tokens', sa.Integer(), nullable=True),
    sa.Column('avg_cost', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('measured_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['ai_prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_prompt_period', 'prompt_metrics', ['prompt_id', 'period'], unique=False)
    op.create_table('readiness_tracker',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('current_stage', sa.Enum('IDEA', 'VALIDATION', 'MVP', 'BETA', 'LAUNCH', 'GROWTH', 'SCALE', name='projectstageenum'), nullable=True),
    sa.Column('stage_pct', sa.Float(), nullable=True),
    sa.Column('requirements_remaining', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_days_to_next', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('idea_criteria_met', sa.Boolean(), nullable=True),
    sa.Column('validation_criteria_met', sa.Boolean(), nullable=True),
    sa.Column('mvp_criteria_met', sa.Boolean(), nullable=True),
    sa.Column('beta_criteria_met', sa.Boolean(), nullable=True),
    sa.Column('launch_criteria_met', sa.Boolean(), nullable=True),
    sa.Column('growth_criteria_met', sa.Boolean(), nullable=True),
    sa.Column('last_ai_check', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index('idx_readiness_project', 'readiness_tracker', ['project_id'], unique=False)
    op.create_table('score_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('gsis_score', sa.Float(), nullable=True),
    sa.Column('unicorn_potential_score', sa.Float(), nullable=True),
    sa.Column('execution_velocity_index', sa.Float(), nullable=True),
    sa.Column('evi_i_adjusted', sa.Float(), nullable=True),
    sa.Column('revenue_growth_signal', sa.Float(), nullable=True),
    sa.Column('beta_satisfaction_score', sa.Float(), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('market_readiness_score', sa.Float(), nullable=True),
    sa.Column('transparency_score', sa.Float(), nullable=True),
    sa.Column('founder_reliability_score', sa.Float(), nullable=True),
    sa.Column('community_influence_score', sa.Float(), nullable=True),
    sa.Column('investor_interest_score', sa.Float(), nullable=True),
    sa.Column('product_progress_score', sa.Float(), nullable=True),
    sa.Column('team_strength_score', sa.Float(), nullable=True),
    sa.Column('investment_score', sa.Float(), nullable=True),
    sa.Column('wcrs_adjusted_score', sa.Float(), nullable=True),
    sa.Column('decay_factor', sa.Float(), nullable=True),
    sa.Column('days_since_update', sa.Integer(), nullable=True),
    sa.Column('quality_flags', sa.Integer(), nullable=True),
    sa.Column('snapshot_trigger', sa.String(length=100), nullable=True),
    sa.Column('alert_score', sa.Float(), nullable=True),
    sa.Column('alert_triggered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_score_gsis', 'score_snapshots', ['gsis_score'], unique=False)
    op.create_index('idx_score_project_created', 'score_snapshots', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_score_user_created', 'score_snapshots', ['user_id', 'created_at'], unique=False)
    op.create_table('solution_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('solution_type', sa.String(length=50), nullable=False),
    sa.Column('funding_type', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=True),
    sa.Column('impact_model', sa.Text(), nullable=True),
    sa.Column('execution_plan', sa.Text(), nullable=True),
    sa.Column('required_roles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('required_resources', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('estimated_cost_usd', sa.DECIMAL(precision=14, scale=2), nullable=True),
    sa.Column('estimated_timeline_weeks', sa.Integer(), nullable=True),
    sa.Column('impact_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('feasibility_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('sustainability_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('readiness_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('contributors', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_solution_created_by', 'solution_projects', ['created_by'], unique=False)
    op.create_index('idx_solution_impact_score', 'solution_projects', ['impact_score'], unique=False)
    op.create_index('idx_solution_problem', 'solution_projects', ['problem_id'], unique=False)
    op.create_index('idx_solution_type_stage', 'solution_projects', ['solution_type', 'stage'], unique=False)
    op.create_table('wcrs_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('base_wcrs', sa.Float(), nullable=False),
    sa.Column('quality_multiplier', sa.Float(), nullable=False),
    sa.Column('decay_factor', sa.Float(), nullable=False),
    sa.Column('adjusted_score', sa.Float(), nullable=False),
    sa.Column('quality_flags', sa.Integer(), nullable=True),
    sa.Column('days_since_update', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wcrs_project_created', 'wcrs_history', ['project_id', 'created_at'], unique=False)
    op.create_table('ai_audio_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ai_output_id', sa.UUID(), nullable=False),
    sa.Column('voice_provider', sa.Enum('ELEVENLABS', 'PLAYHT', 'OPENAI', name='voiceproviderenum'), nullable=False),
    sa.Column('audio_url', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['ai_output_id'], ['ai_outputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audio_output_id', 'ai_audio_outputs', ['ai_output_id'], unique=False)
    op.create_table('discussion_contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('contribution_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ai_quality_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('cluster_label', sa.String(length=100), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('is_ai_summarised', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem_nodes.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['discussion_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contribution_author', 'discussion_contributions', ['author_id'], unique=False)
    op.create_index('idx_contribution_quality', 'discussion_contributions', ['ai_quality_score'], unique=False)
    op.create_index('idx_contribution_thread', 'discussion_contributions', ['thread_id', 'created_at'], unique=False)
    op.create_index('idx_contribution_type', 'discussion_contributions', ['contribution_type'], unique=False)
    op.create_table('document_exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('export_format', sa.String(length=30), nullable=False),
    sa.Column('export_url', sa.Text(), nullable=True),
    sa.Column('file_size_kb', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('is_shareable', sa.Boolean(), nullable=True),
    sa.Column('share_token', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('downloaded_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['generated_documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_export_document', 'document_exports', ['document_id'], unique=False)
    op.create_index('idx_export_format', 'document_exports', ['export_format'], unique=False)
    op.create_index('idx_export_token', 'document_exports', ['share_token'], unique=False)
    op.create_index('idx_export_user', 'document_exports', ['user_id', 'created_at'], unique=False)
    op.create_table('grant_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('funder_name', sa.String(length=255), nullable=False),
    sa.Column('funding_type', sa.String(length=50), nullable=False),
    sa.Column('amount_requested_usd', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('application_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('decision_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solution_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grant_created_by', 'grant_applications', ['created_by'], unique=False)
    op.create_index('idx_grant_solution', 'grant_applications', ['solution_id'], unique=False)
    op.create_index('idx_grant_status', 'grant_applications', ['status'], unique=False)
    op.create_table('module_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('curriculum_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.String(length=20), nullable=False),
    sa.Column('module_title', sa.String(length=255), nullable=True),
    sa.Column('zone', sa.Enum('PRE_MVP', 'POST_MVP', name='trainingzoneenum'), nullable=True),
    sa.Column('track', sa.Enum('FOUNDER', 'BUILDER', 'INVESTOR', 'HYBRID', 'GROWTH', 'REVENUE', 'FUNDRAISING', 'SCALE', 'OPERATIONS', name='trainingtrackenum'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('quiz_score', sa.Float(), nullable=True),
    sa.Column('exercise_submitted', sa.Boolean(), nullable=True),
    sa.Column('exercise_url', sa.Text(), nullable=True),
    sa.Column('ai_review_result', sa.Text(), nullable=True),
    sa.Column('ai_review_score', sa.Float(), nullable=True),
    sa.Column('self_reported', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('hours_spent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_id'], ['personalised_curricula.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_progress_curriculum_module', 'module_progress', ['curriculum_id', 'module_id'], unique=False)
    op.create_index('idx_progress_user_status', 'module_progress', ['user_id', 'status'], unique=False)
    op.create_table('readiness_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tracker_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('IDEA', 'VALIDATION', 'MVP', 'BETA', 'LAUNCH', 'GROWTH', 'SCALE', name='projectstageenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('ai_inferred', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tracker_id'], ['readiness_tracker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_milestone_tracker_stage', 'readiness_milestones', ['tracker_id', 'stage'], unique=False)
    op.create_table('solution_deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=False),
    sa.Column('deployment_mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('partner_orgs', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('resources_allocated', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('beneficiaries_target', sa.Integer(), nullable=True),
    sa.Column('beneficiaries_reached', sa.Integer(), nullable=True),
    sa.Column('deployment_checklist', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_deployment_plan', sa.Text(), nullable=True),
    sa.Column('readiness_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('target_end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solution_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deployment_region', 'solution_deployments', ['region'], unique=False)
    op.create_index('idx_deployment_solution', 'solution_deployments', ['solution_id'], unique=False)
    op.create_index('idx_deployment_status', 'solution_deployments', ['status'], unique=False)
    op.create_table('field_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('field_report', sa.Text(), nullable=True),
    sa.Column('beneficiary_feedback', sa.Text(), nullable=True),
    sa.Column('impact_metrics', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_points', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('what_worked', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('usage_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['solution_deployments.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solution_projects.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_deployment', 'field_feedback', ['deployment_id'], unique=False)
    op.create_index('idx_feedback_solution', 'field_feedback', ['solution_id'], unique=False)
    op.create_index('idx_feedback_submitted', 'field_feedback', ['submitted_by', 'created_at'], unique=False)
    op.create_table('impact_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=True),
    sa.Column('impact_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('people_affected_estimate', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('severity_score', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('scalability_score', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('sustainability_score', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('measurability_score', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('priority_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('priority_colour', sa.String(length=10), nullable=True),
    sa.Column('beneficiaries_reached', sa.Integer(), nullable=True),
    sa.Column('funds_deployed_usd', sa.DECIMAL(precision=14, scale=2), nullable=True),
    sa.Column('snapshot_notes', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['solution_deployments.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solution_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_impact_snapshot_score', 'impact_snapshots', ['impact_score'], unique=False)
    op.create_index('idx_impact_snapshot_solution', 'impact_snapshots', ['solution_id', 'computed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_impact_snapshot_solution', table_name='impact_snapshots')
    op.drop_index('idx_impact_snapshot_score', table_name='impact_snapshots')
    op.drop_table('impact_snapshots')
    op.drop_index('idx_feedback_submitted', table_name='field_feedback')
    op.drop_index('idx_feedback_solution', table_name='field_feedback')
    op.drop_index('idx_feedback_deployment', table_name='field_feedback')
    op.drop_table('field_feedback')
    op.drop_index('idx_deployment_status', table_name='solution_deployments')
    op.drop_index('idx_deployment_solution', table_name='solution_deployments')
    op.drop_index('idx_deployment_region', table_name='solution_deployments')
    op.drop_table('solution_deployments')
    op.drop_index('idx_milestone_tracker_stage', table_name='readiness_milestones')
    op.drop_table('readiness_milestones')
    op.drop_index('idx_progress_user_status', table_name='module_progress')
    op.drop_index('idx_progress_curriculum_module', table_name='module_progress')
    op.drop_table('module_progress')
    op.drop_index('idx_grant_status', table_name='grant_applications')
    op.drop_index('idx_grant_solution', table_name='grant_applications')
    op.drop_index('idx_grant_created_by', table_name='grant_applications')
    op.drop_table('grant_applications')
    op.drop_index('idx_export_user', table_name='document_exports')
    op.drop_index('idx_export_token', table_name='document_exports')
    op.drop_index('idx_export_format', table_name='document_exports')
    op.drop_index('idx_export_document', table_name='document_exports')
    op.drop_table('document_exports')
    op.drop_index('idx_contribution_type', table_name='discussion_contributions')
    op.drop_index('idx_contribution_thread', table_name='discussion_contributions')
    op.drop_index('idx_contribution_quality', table_name='discussion_contributions')
    op.drop_index('idx_contribution_author', table_name='discussion_contributions')
    op.drop_table('discussion_contributions')
    op.drop_index('idx_audio_output_id', table_name='ai_audio_outputs')
    op.drop_table('ai_audio_outputs')
    op.drop_index('idx_wcrs_project_created', table_name='wcrs_history')
    op.drop_table('wcrs_history')
    op.drop_index('idx_solution_type_stage', table_name='solution_projects')
    op.drop_index('idx_solution_problem', table_name='solution_projects')
    op.drop_index('idx_solution_impact_score', table_name='solution_projects')
    op.drop_index('idx_solution_created_by', table_name='solution_projects')
    op.drop_table('solution_projects')
    op.drop_index('idx_score_user_created', table_name='score_snapshots')
    op.drop_index('idx_score_project_created', table_name='score_snapshots')
    op.drop_index('idx_score_gsis', table_name='score_snapshots')
    op.drop_table('score_snapshots')
    op.drop_index('idx_readiness_project', table_name='readiness_tracker')
    op.drop_table('readiness_tracker')
    op.drop_index('idx_metrics_prompt_period', table_name='prompt_metrics')
    op.drop_table('prompt_metrics')
    op.drop_index('idx_milestone_project', table_name='project_milestones')
    op.drop_table('project_milestones')
    op.drop_index('idx_curriculum_user', table_name='personalised_curricula')
    op.drop_table('personalised_curricula')
    op.drop_index('idx_orgmember_org', table_name='org_members')
    op.drop_table('org_members')
    op.drop_index('idx_match_seeker', table_name='matches')
    op.drop_index('idx_match_score', table_name='matches')
    op.drop_table('matches')
    op.drop_index('idx_watchlist_investor', table_name='investor_watchlist')
    op.drop_table('investor_watchlist')
    op.drop_index('idx_evi_signal', table_name='investor_evi_snapshots')
    op.drop_index('idx_evi_project_computed', table_name='investor_evi_snapshots')
    op.drop_index('idx_evi_adjusted', table_name='investor_evi_snapshots')
    op.drop_table('investor_evi_snapshots')
    op.drop_index('idx_alert_investor_read', table_name='investor_alerts')
    op.drop_table('investor_alerts')
    op.drop_index('idx_idea_project', table_name='idea_embeddings')
    op.drop_index('idx_idea_fingerprint', table_name='idea_embeddings')
    op.drop_table('idea_embeddings')
    op.drop_index('idx_doc_user', table_name='generated_documents')
    op.drop_index('idx_doc_type_audience', table_name='generated_documents')
    op.drop_index('idx_doc_project_type', table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_index('idx_feed_relevance', table_name='feed_posts')
    op.drop_index('idx_feed_author', table_name='feed_posts')
    op.drop_table('feed_posts')
    op.drop_index('idx_event_user', table_name='event_logs')
    op.drop_index('idx_event_type_created', table_name='event_logs')
    op.drop_index('idx_event_processed', table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index('idx_eval_score', table_name='evaluations')
    op.drop_index('idx_eval_project', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index('idx_thread_ready', table_name='discussion_threads')
    op.drop_index('idx_thread_problem', table_name='discussion_threads')
    op.drop_table('discussion_threads')
    op.drop_index('idx_scaffold_user', table_name='app_scaffolds')
    op.drop_index('idx_scaffold_type_status', table_name='app_scaffolds')
    op.drop_index('idx_scaffold_project', table_name='app_scaffolds')
    op.drop_table('app_scaffolds')
    op.drop_index('idx_output_user_created', table_name='ai_outputs')
    op.drop_index('idx_output_task_type', table_name='ai_outputs')
    op.drop_index('idx_output_project', table_name='ai_outputs')
    op.drop_index('idx_output_cost', table_name='ai_outputs')
    op.drop_table('ai_outputs')
    op.drop_index('idx_agent_user_started', table_name='agent_execution_logs')
    op.drop_index('idx_agent_type_started', table_name='agent_execution_logs')
    op.drop_index('idx_agent_success', table_name='agent_execution_logs')
    op.drop_table('agent_execution_logs')
    op.drop_index('idx_user_embedding', table_name='user_skill_embeddings')
    op.drop_table('user_skill_embeddings')
    op.drop_index('idx_referral_referrer', table_name='referral_events')
    op.drop_table('referral_events')
    op.drop_index('idx_project_wcrs', table_name='projects')
    op.drop_index('idx_project_stage', table_name='projects')
    op.drop_index('idx_project_owner', table_name='projects')
    op.drop_index('idx_project_gsis', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_problem_submitted_by', table_name='problem_nodes')
    op.drop_index('idx_problem_priority_score', table_name='problem_nodes')
    op.drop_index('idx_problem_impact_score', table_name='problem_nodes')
    op.drop_index('idx_problem_category_urgency', table_name='problem_nodes')
    op.drop_table('problem_nodes')
    op.drop_index('idx_paywall_user', table_name='paywall_hits')
    op.drop_index('idx_paywall_operation', table_name='paywall_hits')
    op.drop_table('paywall_hits')
    op.drop_index('idx_org_owner', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('idx_learner_user', table_name='learner_profiles')
    op.drop_table('learner_profiles')
    op.drop_index('idx_template_type_audience_style', table_name='document_templates')
    op.drop_index('idx_template_active', table_name='document_templates')
    op.drop_table('document_templates')
    op.drop_index('idx_purchase_user', table_name='credit_purchases')
    op.drop_table('credit_purchases')
    op.drop_index('idx_credit_user_created', table_name='credit_ledger')
    op.drop_index('idx_credit_event_type', table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index('idx_prompt_version', table_name='ai_prompts')
    op.drop_index('idx_prompt_type_role', table_name='ai_prompts')
    op.drop_table('ai_prompts')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
