"""fix_embeddings

Revision ID: 79e83ff518e5
Revises: 323a1fc13be9
Create Date: 2026-04-13 22:03:39.670224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79e83ff518e5'
down_revision: Union[str, None] = '323a1fc13be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idea_embeddings', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.alter_column('user_skill_embeddings', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_skill_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
    op.alter_column('idea_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
    # ### end Alembic commands ###
